# fly.toml app configuration file generated for crab-url on 2023-08-30T17:44:32+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "crab-url"
primary_region = "mad"

[build]

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]
